### ISSUE TITLE
New release for dotty changes

### ISSUE THREAD

**Issue by ghost** [fiadliel/sbt-partial-unification#7]
ref chat at https://gitter.im/lampepfl/dotty?at=5b41cbd43d8f71623d65c98f

If you could do a new release, please, we can start looking at dotty cats.  :smile:

**Comment by ghost** [comment]
specifically, when https://github.com/typelevel/cats/pull/2323 is merged

**Comment by fiadliel** [comment]
Released 1.1.2, please try 😄

**Comment by ghost** [comment]
Awesome, thanks!!!
